# Generated by Django 3.1.2 on 2020-10-12 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('key', models.CharField(max_length=30)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2020, 10, 12, 20, 24, 27, 111729, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
