# Generated by Django 3.1.2 on 2020-10-13 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 21, 12, 37, 289623, tzinfo=utc)),
        ),
    ]
