# Generated by Django 3.1.2 on 2020-10-11 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201008_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailkey',
            old_name='email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='emailkey',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 22, 26, 20, 444090, tzinfo=utc)),
        ),
    ]
