# Generated by Django 3.1.2 on 2020-10-13 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201013_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 21, 48, 2, 356824, tzinfo=utc)),
        ),
    ]
