# Generated by Django 3.0.5 on 2020-10-14 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201013_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 11, 47, 23, 27431, tzinfo=utc)),
        ),
    ]
