# Generated by Django 3.1.2 on 2020-10-14 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201014_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 22, 1, 11, 388008, tzinfo=utc)),
        ),
    ]
